// flow-typed signature: 1c79d6fc88bb335b2bdfd6e76e1d4af1
// flow-typed version: <<STUB>>/markdown-react-js_v^0.3.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-react-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-react-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-react-js/babelhook' {
  declare module.exports: any;
}

declare module 'markdown-react-js/dist/markdown-react.min' {
  declare module.exports: any;
}

declare module 'markdown-react-js/lib/index' {
  declare module.exports: any;
}

declare module 'markdown-react-js/test/test' {
  declare module.exports: any;
}

declare module 'markdown-react-js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-react-js/babelhook.js' {
  declare module.exports: $Exports<'markdown-react-js/babelhook'>;
}
declare module 'markdown-react-js/dist/markdown-react.min.js' {
  declare module.exports: $Exports<'markdown-react-js/dist/markdown-react.min'>;
}
declare module 'markdown-react-js/lib/index.js' {
  declare module.exports: $Exports<'markdown-react-js/lib/index'>;
}
declare module 'markdown-react-js/test/test.js' {
  declare module.exports: $Exports<'markdown-react-js/test/test'>;
}
declare module 'markdown-react-js/webpack.config.js' {
  declare module.exports: $Exports<'markdown-react-js/webpack.config'>;
}
